DROP TABLE IF EXISTS PLAYER_INFO;
CREATE TABLE PLAYER_INFO(     
    PLAYERTEAM      VARCHAR(80)     COMMENT    '球队',
    PLAYERNAME      VARCHAR(100)    COMMENT  '球员姓名',
    PLAYERJOB       VARCHAR(20)     COMMENT  '球员位置',
    PLAYERTALL      VARCHAR(20)     COMMENT  '球员身高',
    PLAYERWEIGHT    VARCHAR(20)     COMMENT  '球员体重',
    PLAYERBIRTHDAY  VARCHAR(20)     COMMENT  '球员生日',
    PLAYERNUMBER    VARCHAR(20)     COMMENT   '球员号码',
    PLAYERIMG       VARCHAR(1000)   COMMENT  '球员照片',
    PLAYERCONT      VARCHAR(1000)   COMMENT  '球员合同',
    PLAYERSAL       VARCHAR(2000)   COMMENT  '球员年薪',
    PRIMARY KEY (PLAYERTEAM,PLAYERNUMBER)
   )ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='球员信息';
   
   
DROP TABLE IF EXISTS FOOTBALL_INFO;
CREATE TABLE FOOTBALL_INFO(     
    LEAGUE      VARCHAR(80)       COMMENT   '联赛名称',
    TEAM_NAME   VARCHAR(200)      COMMENT   '球队名称',
    PLAYER_NUMBER VARCHAR(20)     COMMENT   '球员号码',
    PLAYER_CHA_NAME VARCHAR(200)  COMMENT   '球员中文名',
    PLAYER_ENG_NAME VARCHAR(200)  COMMENT   '球员英文名',
    PLAYER_AGE   VARCHAR(20)      COMMENT   '球员年龄',
    PLAYER_COURTRY VARCHAR(100)   COMMENT   '球员所属国籍',
    PLAYER_JOB  VARCHAR(80)       COMMENT   '球员位置', 
    TEAM_LOGO  VARCHAR(200)  COMMENT   '球队LOGO',
    TEAM_COACH VARCHAR(200)  COMMENT   '球队教练',
    TEAM_BUILD VARCHAR(200)  COMMENT   '成立时间',
    TEAM_CITY  VARCHAR(200)  COMMENT   '所在城市',
    TEAM_PLACE VARCHAR(200)  COMMENT   '主球场',
    TEAM_ADDR  VARCHAR(200)  COMMENT   '联系地址',
    TEAM_HREF  VARCHAR(200)  COMMENT   '官网',  
    PRIMARY KEY (LEAGUE,TEAM_NAME,PLAYER_ENG_NAME,PLAYER_NUMBER)
   )ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='足球信息';
   
   
 DROP TABLE IF EXISTS FOOTBALL_RANK;  
 CREATE TABLE FOOTBALL_RANK(     
    LEAGUE      VARCHAR(80)  COMMENT   '联赛名称',
    RANK        INT          COMMENT   '排名',
    TEAM_NAME   VARCHAR(200) COMMENT   '球队名称',
    PLAY    VARCHAR(50)      COMMENT   '场次',
    WIN     VARCHAR(50)      COMMENT   '胜',
    SAME    VARCHAR(50)      COMMENT   '平',
    LOSS    VARCHAR(50)      COMMENT   '负',
    ALL_WIN_BALL    VARCHAR(50)      COMMENT   '进球',
    LOSS_BALL       VARCHAR(50)      COMMENT   '失球',
    GOAL_BALL       VARCHAR(50)      COMMENT   '净胜球',
    SCORE           VARCHAR(50)      COMMENT   '积分',
    PRIMARY KEY (LEAGUE,RANK,TEAM_NAME)
   )ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='联赛积分榜';
   
DROP TABLE IF EXISTS FOOTBALL_SCORES;
CREATE TABLE FOOTBALL_SCORES( 
    LEAGUE      VARCHAR(80)       COMMENT   '联赛名称',    
    RANK        INT          COMMENT   '排名',
    TEAM_NAME   VARCHAR(200) COMMENT   '球队名称',
    PLAYER_CHA    VARCHAR(200)      COMMENT   '中文名',
    PLAYER_ENG     VARCHAR(200)      COMMENT   '英文名',
    PLAYER_JOB    VARCHAR(200)      COMMENT   '位置',
    COMING_BALL    VARCHAR(50)      COMMENT   '进球数',
    PENALTY_BALL    VARCHAR(50)      COMMENT   '点球数',
    PRIMARY KEY (LEAGUE,RANK,TEAM_NAME,PLAYER_ENG)
   )ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='联赛射手榜';
   
   
   
   
   
   
   
   
   
   
